### ISSUE TITLE
Covert English services files

### ISSUE THREAD

**Issue by typiconman** [slavonic/odt2md#6]
I am trying to convert some English Menaion files using ODT2MD. I get an error message:

```
Traceback (most recent call last):
  File "/home/sasha/.local/bin/odt2md", line 11, in <module>
    sys.exit(main())
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/odt2md.py", line 52, in main
    odt2md(args.input, args.output, profile=args.profile, max_line_width=args.max_line_width)
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/odt2md.py", line 19, in odt2md
    markdown_text = styler.format_md(blocks)
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/styler.py", line 137, in format_md
    for b in blocks:
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/block.py", line 211, in parse_odt
    yield from parse_blocks(para)
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/block.py", line 46, in parse_blocks
    yield from extract_spans(ev.scan(para), para_style)
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/block.py", line 98, in extract_spans
    assert False, e['tag']
AssertionError: {urn:oasis:names:tc:opendocument:xmlns:text:1.0}toc-mark
```

[0701.odt.zip](https://github.com/slavonic/odt2md/files/4760472/0701.odt.zip)

**Comment by pgmmpk** [comment]
fixed. Please update to version 0.0.7

**Comment by typiconman** [comment]
It works, thanks.

**Comment by typiconman** [comment]
So the conversion ignores everything in the ODT file that's in a custom Style. Compare the content.md and ODT files.
[0701.zip](https://github.com/slavonic/odt2md/files/4764690/0701.zip)

**Comment by pgmmpk** [comment]
I see only headers skipped.

The reason is because I was only selecting P elements (still learning the structure of ODT xml).

Now I am doing a more strict parsing... This may cause other failures because now, instead of selecting P, I am iterating thru everything and explicitly skip the elements that have no content, and expect only Ps and Hs to have content.

As of 0.0.8, headers are parsed and added as regular blocks to the markdown.

**Comment by typiconman** [comment]
I think it works. Here is the result: https://github.com/typiconman/english-md
