### ISSUE TITLE
File conversion error

### ISSUE THREAD

**Issue by typiconman** [slavonic/odt2md#7]
I get a strange error when I try to convert the attached file:

```
WARNING:root:Undefined style name: 'C1'
WARNING:root:Undefined style name: 'lesson'
WARNING:root:Undefined style name: 'Standard'
Traceback (most recent call last):
  File "/home/sasha/.local/bin/odt2md", line 11, in <module>
    sys.exit(main())
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/odt2md.py", line 52, in main
    odt2md(args.input, args.output, profile=args.profile, max_line_width=args.max_line_width)
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/odt2md.py", line 19, in odt2md
    markdown_text = styler.format_md(blocks)
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/styler.py", line 137, in format_md
    for b in blocks:
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/block.py", line 224, in parse_odt
    yield from parse_blocks(para)
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/block.py", line 46, in parse_blocks
    yield from extract_spans(ev.scan(para), para_style)
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/block.py", line 98, in extract_spans
    assert False, e['tag']
AssertionError: {urn:oasis:names:tc:opendocument:xmlns:text:1.0}bookmark-start
```

Something having to do with bookmarks?
[out.odt.zip](https://github.com/slavonic/odt2md/files/4917077/out.odt.zip)

**Comment by pgmmpk** [comment]
Yes, bookmarks were not expected. Added bookmark-start and bookmark-end to the list of ignored tags (I do not think we can use this info in MD). Version 0.0.9 is published, please try.

**Comment by typiconman** [comment]
This particular file works fine, but now there is an error when I convert another file. Also has something to do with bookmarks.
```
Convering 10/06.12 John et al.docx at script.pl line 12.
func=xmlSecCheckVersionExt:file=xmlsec.c:line=188:obj=unknown:subj=unknown:error=19:invalid version:mode=abi compatible;expected minor version=2;real minor version=2;expected subminor version=25;real subminor version=26
Traceback (most recent call last):
  File "/home/sasha/.local/bin/odt2md", line 11, in <module>
    sys.exit(main())
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/odt2md.py", line 52, in main
    odt2md(args.input, args.output, profile=args.profile, max_line_width=args.max_line_width)
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/odt2md.py", line 19, in odt2md
    markdown_text = styler.format_md(blocks)
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/styler.py", line 137, in format_md
    for b in blocks:
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/block.py", line 231, in parse_odt
    yield from parse_blocks(para)
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/block.py", line 46, in parse_blocks
    yield from extract_spans(ev.scan(para), para_style)
  File "/home/sasha/.local/lib/python3.6/site-packages/odt2md/block.py", line 105, in extract_spans
    assert False, e['tag']
AssertionError: {urn:oasis:names:tc:opendocument:xmlns:text:1.0}bookmark
```
Edit: sorry, here is the ODT, not the original DOCX.
[out.odt.zip](https://github.com/slavonic/odt2md/files/4926320/out.odt.zip)

**Comment by pgmmpk** [comment]
Right, another XML tag learned :/. I added this one to the ignored list too. Should work now. By and by we will learn all possible ODT tags...

Pushed 0.0.10 to the PyPi, please upgrade.

**Comment by typiconman** [comment]
Yes, now it works OK, thanks.
